-- Generated by Oracle SQL Developer Data Modeler 
--   at:        2020-04-17 14:08:49 BST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
--Author: Markus Baciu(C18350801)
--Description: Tables created from ERD for Automated Exams



CREATE TABLE class (
    classid    NUMBER(5) NOT NULL,
    classsize  NUMBER(2)
);

ALTER TABLE class ADD CONSTRAINT class_pk PRIMARY KEY ( classid );

CREATE TABLE exam (
    examid               NUMBER(5) NOT NULL,
    examsession          VARCHAR2(6) NOT NULL,
    examdate             DATE NOT NULL,
    starttime            number(4) NOT NULL,
    examduration         number(4) NOT NULL,
    compulsory           CHAR(1) NOT NULL,
    audio                CHAR(1),
    graphics             CHAR(1),
    question_questionno  NUMBER(2) NOT NULL
);

ALTER TABLE exam ADD CONSTRAINT exam_pk PRIMARY KEY ( examid );

CREATE TABLE question (
    questionno     NUMBER(2) NOT NULL,
    questiontype   VARCHAR2(10) NOT NULL,
    questionans    VARCHAR2(50) NOT NULL,
    questionscore  NUMBER(2) NOT NULL
);

ALTER TABLE question ADD CONSTRAINT question_pk PRIMARY KEY ( questionno );

CREATE TABLE student (
    studentid      VARCHAR2(5) NOT NULL,
    saddress       VARCHAR2(50),
    studentname    VARCHAR2(10) NOT NULL,
    class_classid  NUMBER(5) NOT NULL
);

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( studentid );

CREATE TABLE subject (
    subjectid    VARCHAR2(5) NOT NULL,
    subjectname  VARCHAR2(10),
    exam_examid  NUMBER(5) NOT NULL
);

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( subjectid );

CREATE TABLE teacher (
    teacherid          VARCHAR2(5) NOT NULL,
    teachername        VARCHAR2(20),
    subject_subjectid  VARCHAR2(5) NOT NULL,
    class_classid      NUMBER(5) NOT NULL
);

ALTER TABLE teacher ADD CONSTRAINT teacher_pk PRIMARY KEY ( teacherid );

ALTER TABLE exam
    ADD CONSTRAINT exam_question_fk FOREIGN KEY ( question_questionno )
        REFERENCES question ( questionno );

ALTER TABLE student
    ADD CONSTRAINT student_class_fk FOREIGN KEY ( class_classid )
        REFERENCES class ( classid );

ALTER TABLE subject
    ADD CONSTRAINT subject_exam_fk FOREIGN KEY ( exam_examid )
        REFERENCES exam ( examid );

ALTER TABLE teacher
    ADD CONSTRAINT teacher_class_fk FOREIGN KEY ( class_classid )
        REFERENCES class ( classid );

ALTER TABLE teacher
    ADD CONSTRAINT teacher_subject_fk FOREIGN KEY ( subject_subjectid )
        REFERENCES subject ( subjectid );

commit;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
